import { makeStyles } from "@mui/styles";
import HeroBg from "../public/assets/desktop/HeroBlackBg.png";
import InvestBgImg from "../public/assets/desktop/InvestBgImg.png";

export const useStyles = makeStyles((theme) => ({
  fullHero: {
    position: "relative",
    top: "-0.2vw",
  },
  heroBg: {
    position: "relative",
    zIndex: "-1",
    width: "100%",
    left: "0",
  },
  heroHeading: {
    position: "absolute",
    width: "70.5vw",
    left: "50%",
    transform: "translateX(-50%)",
    color: "#fff",
    top: "8.89vw",
    textAlign: "center",
    fontWeight: "700",
    // fontSize: "5.75rem",
    fontSize: "5.75vw",
    lineHeight: "107.5%",
  },
  heroDescription: {
    position: "absolute",
    width: "47vw",
    left: "50%",
    transform: "translateX(-50%)",
    color: "#fff",
    top: "23.89vw",
    textAlign: "center",
    // fontSize: "1.45rem",
    fontSize: "1.48vw",
    lineHeight: "125%",
  },
  heroButtons: {
    position: "absolute",
    left: "49%",
    transform: "translateX(-50%)",
    top: "32.5vw",
    display: "flex",
    justifyContent: "space-around",
    width: "38%",
  },
  heroBtn: {
    color: "#fff",
    textTransform: "none",
    fontWeight: "400",
    // fontSize: "1.57rem",
    fontSize: "1.57vw",
    fontFamily: "'Euclid Circular A', sans-serif",
    margin: "0 0.6rem 0 1.5rem",
    borderRadius: "100rem",
    padding: "0.56vw 2.1vw",
    border: "2px solid" + theme.palette.primary.main,
    backgroundColor: theme.palette.primary.main,
    "&:hover": {
      backgroundColor: "transparent",
      border: "2px solid" + theme.palette.primary.main,
    },
  },
  heroBtn_getStarted: {
    fontWeight: "500",
    color: "#000",
    border: "2px solid" + theme.palette.alternate.main,
    backgroundColor: theme.palette.alternate.main,
    "&:hover": {
      color: theme.palette.alternate.main,
      backgroundColor: "transparent",
      border: "2px solid" + theme.palette.alternate.main,
    },
  },

  //   Section 01
  section01Img: {
    position: "relative",
    width: "57%",
    marginLeft: "2vw",
  },
  sectionContentDiv: {
    position: "relative",
    left: "3.5vw",
    width: "80%",
  },
  sectionNumber: {
    marginBottom: "1.65vw",
    fontSize: "1.4rem",
    fontWeight: "700",
    fontFamily: "'Helvetica', sans-serif",
  },
  sectionHeading: {
    position: "relative",
    display: "block",
    fontSize: "3.6vw",
    fontWeight: "500",
    lineHeight: "104%",
  },
  sectionDescription: {
    position: "relative",
    top: "1.8rem",
    display: "block",
    fontSize: "1.325vw",
    fontWeight: "500",
    width: "81%",
    lineHeight: "122.5%",
  },
  sectionHorizontalLine: {
    position: "relative",
    width: "35%",
    left: "-6.5vw",
    top: "4.5rem",
    border: "none",
    borderBottom: "2px solid #000",
  },
  // Section  02
  section02Img: {
    position: "relative",
    width: "64%",
    marginRight: "2vw",
  },
  section02ContentDiv: {
    position: "relative",
    left: "11vw",
    top: "3.5vw",
    width: "80%",
  },
  section02Description: {
    position: "relative",
    top: "1.8rem",
    display: "block",
    fontSize: "1.325vw",
    fontWeight: "500",
    width: "84%",
    lineHeight: "122.5%",
  },
  section02HorizontalLine: {
    position: "relative",
    width: "35%",
    left: "-10vw",
    top: "4.5rem",
    border: "none",
    borderBottom: "2px solid #000",
  },
  sectionContributorBtn: {
    position: "relative",
    marginTop: "6.7rem",
    marginLeft: "2.5rem",
    color: "#fff",
    textTransform: "none",
    fontWeight: "400",
    // fontSize: "1.57rem",
    fontSize: "1.57vw",
    fontFamily: "'Euclid Circular A', sans-serif",
    margin: "0 0.6rem 0 1.5rem",
    borderRadius: "100rem",
    padding: "0.5vw 2.1vw",
    border: "2px solid" + theme.palette.primary.main,
    backgroundColor: theme.palette.primary.main,
    "&:hover": {
      backgroundColor: "#121ac9",
      border: "2px solid #121ac9",
    },
  },

  // Invest Section
  investSection: {
    position: "relative",
    marginTop: "2.5vw",
    paddingBottom: "0",
    height: "120vh",
  },
  investSectionHeading: {
    position: "relative",
    top: "5.4vw",
    color: "#fff",
    fontSize: "3.72vw",
  },

  //Our Vision
  ourVisionImg: {
    width: "120%",
  },
  ourVisionContentDiv: {
    position: "relative",
    left: "2.5rem",
    top: "7vw",
    width: "80%",
  },

  // Newsletter
  newsletterContentDiv: {
    position: "relative",
    left: "11.6vw",
    width: "72%",
  },
  newsletterHeading: {
    position: "relative",
    display: "block",
    fontSize: "3.35vw",
    fontWeight: "500",
    lineHeight: "107.5%",
    color: theme.palette.primary.main,
  },
  newsletterDescription: {
    position: "relative",
    top: "1.8vw",
    display: "block",
    fontSize: "1.325vw",
    fontWeight: "500",
    width: "78%",
    lineHeight: "122.5%",
  },
  newsletterTextField: {
    position: "relative",
    top: "2vw",
    width: "20vw",
  },
  subscribeBtn: {
    position: "relative",
    display: "block",
    marginTop: "4vw",
    color: "#fff",
    textTransform: "none",
    fontWeight: "400",
    // fontSize: "1.57rem",
    fontSize: "1.15vw",
    fontFamily: "'Euclid Circular A', sans-serif",
    borderRadius: "0.5rem",
    padding: "0.5vw 4.3vw",
    border: "2px solid" + theme.palette.primary.main,
    backgroundColor: theme.palette.primary.main,
    "&:hover": {
      backgroundColor: "#121ac9",
      border: "2px solid #121ac9",
    },
  },
}));
